version: '3'
services:
  app:
    image: andersonalmada/custom-annotation
    environment:
      OTEL_SERVICE_NAME: "custom-annotation"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"        
    ports:
      - "8080:8080"
    depends_on:
      - collector

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
 
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
 
  collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    ports:
      - "4318:4318"
      - "4317:4317"
      - "8889:8889" 
